# Generated by Django 6.0.1 on 2026-01-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField()),
                ('url', models.URLField(max_length=1000)),
                ('old_url', models.URLField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
    ]
