# Generated by Django 6.0.1 on 2026-01-28 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='defaults',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
